In [26]:
import os
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
from scipy.optimize import differential_evolution
from codes.gnbg_python.GNBG_instances import GNBG
# Define the path to the folder where you want to read/write files
folder_path = "codes/gnbg_python"

# Initialization
ProblemIndex = 13 # Choose a problem instance range from f1 to f24

# Preparation and loading of the GNBG parameters based on the chosen problem instance
if 1 <= ProblemIndex <= 24:
    filename = f'f{ProblemIndex}.mat'
    GNBG_tmp = loadmat(os.path.join(folder_path, filename))['GNBG']
    MaxEvals = np.array([item[0] for item in GNBG_tmp['MaxEvals'].flatten()])[0, 0]
    AcceptanceThreshold = np.array([item[0] for item in GNBG_tmp['AcceptanceThreshold'].flatten()])[0, 0]
    Dimension = np.array([item[0] for item in GNBG_tmp['Dimension'].flatten()])[0, 0]
    CompNum = np.array([item[0] for item in GNBG_tmp['o'].flatten()])[0, 0]  # Number of components
    MinCoordinate = np.array([item[0] for item in GNBG_tmp['MinCoordinate'].flatten()])[0, 0]
    MaxCoordinate = np.array([item[0] for item in GNBG_tmp['MaxCoordinate'].flatten()])[0, 0]
    CompMinPos = np.array(GNBG_tmp['Component_MinimumPosition'][0, 0])
    CompSigma = np.array(GNBG_tmp['ComponentSigma'][0, 0], dtype=np.float64)
    CompH = np.array(GNBG_tmp['Component_H'][0, 0])
    Mu = np.array(GNBG_tmp['Mu'][0, 0])
    Omega = np.array(GNBG_tmp['Omega'][0, 0])
    Lambda = np.array(GNBG_tmp['lambda'][0, 0])
    RotationMatrix = np.array(GNBG_tmp['RotationMatrix'][0, 0])
    OptimumValue = np.array([item[0] for item in GNBG_tmp['OptimumValue'].flatten()])[0, 0]
    OptimumPosition = np.array(GNBG_tmp['OptimumPosition'][0, 0])
else:
    raise ValueError('ProblemIndex must be between 1 and 24.')

gnbg = GNBG(MaxEvals, AcceptanceThreshold, Dimension, CompNum, MinCoordinate, MaxCoordinate, CompMinPos, CompSigma, CompH, Mu, Omega, Lambda, RotationMatrix, OptimumValue, OptimumPosition)

In [27]:
vectors = []
file_path = 'codes/gnbg_python/vec 3/f_13_param.txt'
with open(file_path, 'r') as f:
    for line in f:
        # Convert comma-separated string to float array
        vector = np.fromstring(line.strip(), sep=',')
        vectors.append(vector)

# Now `vectors` is a list of NumPy arrays
print(f"Loaded {len(vectors)} vectors.")
results = [gnbg.fitness(vec) for vec in vectors]

Loaded 31 vectors.
GNBG.fitness called with X shape: (1, 30), self.FE: 0, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 1, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 2, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 3, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 4, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 5, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 6, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 7, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 8, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 9, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 10, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 11, self.MaxEvals: 500000
GNBG.fitness called with X shape: (1, 30), self.FE: 12,

In [11]:
results

[array([-4451.54352496]),
 array([-4399.89998331]),
 array([-4399.89989705]),
 array([-4456.08975784]),
 array([-4999.991895]),
 array([-4453.92473379]),
 array([-4461.0101884]),
 array([-4999.99709922]),
 array([-4467.61965485]),
 array([-4399.89993269]),
 array([-4399.89998749]),
 array([-4470.38905265]),
 array([-3889.48469495]),
 array([-4764.97194848]),
 array([-3937.90519755]),
 array([-4009.98689624]),
 array([-3886.76630867]),
 array([-4755.26736697]),
 array([-4894.92474543]),
 array([-4068.19991234]),
 array([-4162.57739895]),
 array([-4130.13780203]),
 array([-4702.5468423]),
 array([-4014.67239528]),
 array([-4140.65932519]),
 array([-4027.77829015]),
 array([-4141.74971163]),
 array([-4055.39877626]),
 array([-4189.55855468]),
 array([-3946.80504199]),
 array([-3881.67653666])]

In [28]:
results
with open("output.txt", "w") as f:
    for val in results:
        f.write(f"{val[0]}\n")

In [19]:
vectors = []
with open("codes/gnbg_python/fitness_values/f_15_value.txt", "r") as file:
    for line in file:
        value = float(line.strip())
        vectors.append(value)
errors = gnbg.OptimumValue + vectors
errors

with open("output.txt", "w") as f:
    for val in errors:
        f.write(f"{val}\n")

ValueError: could not convert string to float: ''